#!/usr/bin/env python
"""
Upgrade compatibility: the current binary must run on a data directory written by the previous
release (integration_tests/fixtures/release_<tag>/, generated by fixtures/make_release_fixture.py):

  - the old config validates and the daemon starts on the old databases
  - the old run's report and file list are readable
  - an incremental backup on top of the old database finishes without errors
  - a restore from that new run returns the tree

There is no schema versioning in the database package today; when the schema changes this is the
test that forces an upgrade path instead of a silent break.
"""
import glob
import json
import os
import platform
import shlex
import shutil
import tempfile

import pytest

from common import *

FIXTURES = sorted(glob.glob(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fixtures", "release_*")))
JOB = "first_backup"


def load_meta(fixture_dir):
    with open(os.path.join(fixture_dir, "meta.json"), encoding="utf-8") as fd:
        return json.load(fd)


@pytest.mark.parametrize("fixture_dir", FIXTURES, ids=[os.path.basename(f) for f in FIXTURES])
def test_current_binary_runs_on_previous_release_data(fixture_dir):
    meta = load_meta(fixture_dir)
    if meta["platform"] != platform.system():
        pytest.skip("fixture {} was generated on {}".format(os.path.basename(fixture_dir), meta["platform"]))

    # recreate the tree exactly where the old databases expect it
    from make_release_fixture_shim import build_tree  # noqa: F401  (see conftest: fixtures/ is on sys.path)
    tree_root = meta["tree_root"]
    build_tree(tree_root)

    workspace = tempfile.mkdtemp(prefix="integration_test_compat_")
    data_dir = os.path.join(workspace, "data")
    shutil.copytree(os.path.join(fixture_dir, "data"), data_dir)
    persist_dir = os.path.join(workspace, "objects")
    restore_dir = os.path.join(workspace, "restore")
    config_path = os.path.join(workspace, "config.yaml")
    with open(os.path.join(fixture_dir, "config.yaml")) as fd:
        parsed = yaml.load(fd, Loader=yaml.SafeLoader)
    parsed["data_dir"] = data_dir
    with open(config_path, "w") as fd:
        fd.write(yaml.dump(parsed))
    add_persist_dir_to_null_targets(config_path, persist_dir)

    # the previous release's config is still a valid config
    run_cli("server config validate -c " + shlex.quote(config_path))

    daemon = BackupDaemon(config_path=config_path, extra_options="--logfile=" + os.path.join(workspace, "server.log"))
    try:
        api = ApiClient(daemon.base_url)
        old_job = meta["job_id"]

        # the old run is visible and its report reads back with the counters recorded at generation time
        listed = api.post("/report/backup/list", {"name": JOB})["result"]
        assert [r["job_id"] for r in listed] == [old_job], listed
        assert listed[0]["state"] == "finished"
        old_report = api.backup_report(JOB, old_job)
        assert old_report["stats_counters"] == meta["stats_counters"], old_report
        files = api.post("/report/backup/file/list",
                         {"name": JOB, "job_id": old_job, "path": tree_root, "descend": True})["result"]
        assert files, "file list of the old run is empty"

        # a new run on top of the old database: one file changed, the rest must be recognised as known
        changed = os.path.join(tree_root, "dir1", "dir2", "file1.txt")
        with open(changed, "a", encoding="utf-8") as fd:
            fd.write("\nchanged after the upgrade\n")
        new_job = api.run_backup_and_wait(JOB)
        stats = api.backup_report(JOB, new_job)["stats_counters"]
        num_files, num_dirs, _ = count_files_folders_links(tree_root)
        assert_counters(api, stats, {
            "examined_files": num_files, "examined_directories": num_dirs,
            "failed_to_upload_files": 0, "failed_to_examine": 0, "failed_to_enumerate": 0,
            "database_copy_errors": 0, "marked_deleted_files": 0,
        }, "incremental run over {} data: ".format(meta["version"]))
        assert stats["uploaded_files"] >= 1, stats
        # every file was either re-uploaded, metadata-refreshed, or found up to date: none fell through the cracks
        assert stats["uploaded_files"] + stats["updated_metadata_for_files"] + stats["up_to_date_files"] == num_files, stats
        assert stats["up_to_date_files"] + stats["updated_metadata_for_files"] >= num_files - 1, \
            "the old database's records were not reused for unchanged files: {}".format(stats)
        assert [r["job_id"] for r in api.post("/report/backup/list", {"name": JOB})["result"]] == [old_job, new_job]

        # the changed file restores from the new run. (Unchanged files reference objects uploaded by the
        # old binary into its own store, which this fixture cannot carry, so only the new upload is checked.)
        restore_id = api.start_restore(JOB, new_job, restore_dir, files=[changed])
        api.wait_restore_finishes(JOB, restore_id)
        restored = map_path_into_restore_dir(restore_dir, changed)
        assert os.path.isfile(restored) and get_md5_sum(restored) == get_md5_sum(changed)
        assert api.restore_report(JOB, restore_id)["state"] == "finished"
    finally:
        daemon.kill()
        shutil.rmtree(workspace, ignore_errors=True)
        shutil.rmtree(tree_root, ignore_errors=True)
