---
# global settings affect all backups and can't be specified per backup with different values
# section specific settings are repetitive and can't be overridden by globals
# clarity and safety are paramount to the design so repeating a particular key - value over and over is acceptable
#
#
data_dir: ./tmp/
#defaults to webstatic/ relative to where the cloudbackup binary is located
html_dir: webstatic
user:
  - name: testuser1
    # bcrypt hash of password  "HV}H/y?<9$]Z5N4N" - use ./cloudbackup hash-password to hash passwords
    pass: $2a$05$Ug1eUCXbSYUvfnI6YokjReljCe2fZLYYhO4IQLuiu0/mnpBbsN2M.
    # can be either 'read' or 'write' . 'write' basically gives access to all the API while 'read' only to read-only
    #  operations so for example it excludes things starting/stopping backups or adjusting the configuration
    access: write
  - name: testuser2
    # bcrypt hash of password  "Oonaawai8Eep]eethe8eefa$"
    pass: $2a$05$Pgdwe14mHjOQ33C5LahmmugCY85Yfqlkj2rGvbDMGCDXKKwmhbwVC
    access: read
# host and port for the HTTP server; if HTTPS server is enabled then http server is automatically disabled.
# By default HTTP server is enabled and HTTPS is disabled
http:
  bind_address: "127.0.0.1:8080"
#https:
#  enabled: true
#  bind_address: "127.0.0.1:8443"
#  ssl_cert_path: /etc/ssl/cert.crt
#  ssl_key_path: /etc/ssl/cert.key
backup:
  - name: first_backup
    paths:
      - /etc/vim/
      #- /home/aionica/Downloads/FreeBSD-11.1-RELEASE-amd64-dvd1.iso
    # Bourne-Again shell like globing and globstar is supported in the below "exclusions" section.
    # Term	     Meaning
    # *	         matches any sequence of non-path-separators
    # **	     matches any sequence of characters, including path separators
    # ?	         matches any single non-path-separator character
    # [class]	 matches any single non-path-separator character against a class of characters (see below)
    # {alt1,...} matches a sequence of characters if one of the comma-separated alternatives matches
    #
    # Character classes support the following:
    # Class	 Meaning
    # [abc]    matches any single character within the set
    # [a-z]	 matches any single character in the range
    # [^class] matches any single character which does not match the class
    # Example:
    #     - "**/*.txt"  would exclude all .txt files across all directories
    #     - "/var/lib/*.txt" would exclude .txt files only if they are located in "/var/lib/". If .txt files are
    #         located in "/var/lib/something/" then they would not be matched by the exclusion rule
    # If using exclusion rules then please run "cloudbackup client backup dryrun" in order to check that they work as
    #  expected
    exclusions:
      - /etc/systemd/system
      - /etc/alternatives
    dereference: false
    #checksum: true
    target:
      - name: gcp_1
        type: gcp_storage
        # rate limit uploads to the object store. Specified rate in bytes per second or using a unit like KB/MB/GB etc (Example: 231 KB).
        # Leave unset or set to 0 to have unlimited rate
        #ratelimit: 100 KB
        bucket: 'cloudbackup-tests'
        prefix: 'backup/backups-for-server-51'
        parameters:
          - name: type
            value: service_account
          - name: project_id
            value: cloudbackup-493100
          - name: private_key_id
            value: ***REMOVED***
          - name: private_key
            # MUST BE SURROUNDED BY DOUBLE QUOTES (NOT SINGLE QUOTES)
            value: "***REMOVED***"
          - name: client_email
            value: cloudbackup-integration-tests@cloudbackup-493100.iam.gserviceaccount.com
          - name: client_id
            value: 111404560788247469734
          - name: auth_uri
            value: 'https://accounts.google.com/o/oauth2/auth'
          - name: token_uri
            value: 'https://oauth2.googleapis.com/token'
          - name: auth_provider_x509_cert_url
            value: 'https://www.googleapis.com/oauth2/v1/certs'
          - name: client_x509_cert_url
            value: 'https://www.googleapis.com/robot/v1/metadata/x509/cloudbackup-integration-tests%40cloudbackup-493100.iam.gserviceaccount.com'
          - name: storage_class
            value: regional
#          - name: disable_crc32c_hash
#            value: yes
#      - name: aws_2
#        type: test_null
#        user: BLABLA
#        pass: zzzz
#        # rate limit uploads to the object store. Specified rate in bytes per second or using a unit like KB/MB/GB etc (Example: 231 KB).
#        # Leave unset or set to 0 to have unlimited rate
#        ratelimit: 100000 KB
#        bucket: 'myawesome-backup'
#        prefix: 'backup/backups-for-server-51'
#        storage_class: STANDARD
    schedule:
      - '05 01 * * *'
  - name: second_backup
    paths:
      - /etc/
      - /usr/local/etc
      #- /home/aionica/Downloads/FreeBSD-11.1-RELEASE-amd64-dvd1.iso
    # do not follow symbolic links (defaults to true)
    dereference: false
    # use the file's checksum in order to establish if a backup is needed (defaults to false)
    #checksum: true
    target:
      - name: aws_2
        type: test_null
        ratelimit: 1 KB
        bucket: 'aionica-tests'
        prefix: 'backup/backups-for-server-51'
        parameters:
          - name: AWS_ACCESS_KEY_ID
            value: ***REMOVED***
          - name: AWS_SECRET_ACCESS_KEY
            value: ***REMOVED***
          - name: storage_class
            value: STANDARD
          - name: region
            value: us-east-1
#      - name: google_1
#        type: gcp_storage
#        bucket: 'my-google-bucket'
#        prefix: 'backup/backups-for-server-51'
#        parameters:
#          - name: AWS_ACCESS_KEY_ID
#            value: AKIAIOSFODNN7EXAMPLE
#          - name: AWS_SECRET_ACCESS_KEY
#            value: wJalrXUtnFEMI/K7MDENG/bPxRfiCEXAMPLEKEY
#          - name: storage_class
#            value: STANDARD
#    encrypt: true
#    encrypt_pass: '044ewfsoi423092l;dfksdl;fksl;dfks;ld0492'
    schedule:
      - '00 08 01 * *'
      - '00 08 06 * *'
    # defaults to 0 which means unlimited number of versions
    versions_max_num: 10
    # defaults to 0 which means unlimited age
    versions_max_age: 6w
  - name: third_backup
    paths:
      - /etc/vim/
      #- /home/aionica/Downloads/FreeBSD-11.1-RELEASE-amd64-dvd1.iso
    # do not follow symbolic links (defaults to true)
    dereference: false
    # use the file's checksum in order to establish if a backup is needed (defaults to false)
    #checksum: true
    target:
      - name: azure
        type: azure_blob
        #ratelimit: 100 KB
        bucket: 'cloudbackup-aionica-tests'
        prefix: 'backup/backups-for-server-51'
        parameters:
          - name: storage_account
            value: cloudbackuptests
          - name: storage_access_key
            value: '***REMOVED***'
    #    encrypt: true
    #    encrypt_pass: '044ewfsoi423092l;dfksdl;fksl;dfks;ld0492'
    schedule:
      - '00 08 01 * *'
      - '00 08 06 * *'
    # defaults to 0 which means unlimited number of versions
    versions_max_num: 10
    # defaults to 0 which means unlimited age
    versions_max_age: 6w
#    pre_run_script: /usr/bin/id
#notification:
#  email:
#    - server: smtp.gmail.com
#      port: 587
#      to: alexandru@ionica.eu
#      type:
#        - started
#        - finished
#        - failed
#        - cancelled
#        - crashed
#      user: alexandru.ionica.nas@gmail.com
#      pass: ',,Uob:LF7FtLtNEHtP4}'
#  script:
#    - path: /tmp/lala.sh
#      type:
#        - started
#        - finished
#        - failed
#        - cancelled
#        - crashed
