data_dir: ./tmp/
user:
- name: testuser1
  pass: $2a$05$Ug1eUCXbSYUvfnI6YokjReljCe2fZLYYhO4IQLuiu0/mnpBbsN2M.
  access: write
http:
  bind_address: 127.0.0.1:8080
https:
  enabled: false
  bind_address: 127.0.0.1:8449
  ssl_cert_path: ""
  ssl_key_path: ""
backup:
- name: first_backup
  paths:
  - /something
  - /var/lib
  exclusions:
  - /something/else
  - /var/lib/mysql
  target:
  - name: aws_1
    type: aws_s3
    user: BLABLA
    pass: zzzz
    bucket: myawesome-backup
    prefix: backup/backups-for-server-51
    storage_class: standard
  schedule:
  - 05 01 * * *
  encrypt: false
  encrypt_pass: ""
  versioning: false
  versions_max_num: 0
  versions_max_age: ""
- name: second_backup
  paths:
  - /var/log
  - /var/www/html/data/
  exclusions: []
  target:
  - name: aws_2
    type: aws_s3
    user: JOHNDOE
    pass: qwqe
    bucket: some-stuff-goes-here
    prefix: backup/backups-for-server-51
    storage_class: infrequent-access
  - name: google_1
    type: google_cloud_storage
    user: JANEDOE
    pass: 34324fd
    bucket: my-google-bucket
    prefix: backup/backups-for-server-51
    storage_class: standard
  schedule:
  - 00 08 01 * *
  - 00 08 06 * *
  encrypt: true
  encrypt_pass: 044ewfsoi423092l;dfksdl;fksl;dfks;ld0492
  versioning: true
  versions_max_num: 10
  versions_max_age: 6w
