swagger: '2.0'
info:
  description: >-
    This is the API which allows to configure, start, stop backups and view
    reporta
  version: 1.0.0
  title: Cloudbackup API
basePath: /api/v1
tags:
  - name: config
    description: Configuration of the server and backups it does
  - name: backup
    description: 'Start, stop and see the status backups'
  - name: restore
    description: 'Start, stop and see the status restore operations'
  - name: report
    description: Reports about previous backups and restores
schemes:
  - http
  - https
paths:
  /config:
    post:
      tags:
        - config
      summary: Overwrite whole configuration
      description: 'If a password field is specified with value "******" (number of asterisks does not matter as long as it is only asterisks) then the actual password will be copied from the current running configuration. This is because when you fetch the configuration (via GET) passwords do not get printed.'
      operationId: writeAllCfg
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: daemon configuration
          required: true
          schema:
            $ref: '#/definitions/FullConfig'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
    get:
      tags:
        - config
      summary: Get the whole config
      description: 'Get the current active configuration. Password fields will have their values replaced with "**************" despite what the Swagger example shows below.'
      operationId: getAllCfg
      produces:
        - application/json
      security: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponseGetConfig'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
securityDefinitions:
  backup_auth:
    type: basic
    description: Use Basic Authentication
definitions:
  FullConfig:
    type: object
    properties:
      data_dir:
        type: string
        example: /var/lib/cloudbackup
      user:
        type: array
        items:
          $ref: '#/definitions/User'
      http:
        $ref: '#/definitions/Http'
      https:
        $ref: '#/definitions/Https'
      backup:
        type: array
        items:
          $ref: '#/definitions/Backup'
  User:
    type: object
    properties:
      name:
        type: string
        example: john
      pass:
        type: string
        example: HV}H/y?<9$]Z5N4N
      access:
        type: string
        example: write
        pattern: '^(read|write)$'
  Http:
    type: object
    properties:
      bind_address:
        type: string
        default: '127.0.0.1:8080'
        example: '127.0.0.1:8080'
  Https:
    type: object
    properties:
      enabled:
        type: boolean
        default: false
      bind_address:
        type: string
        default: '127.0.0.1:8443'
        example: '127.0.0.1:8443'
      ssl_cert_path:
        type: string
        example: /etc/ssl/cert.crt
      ssl_key_path:
        type: string
        example: /etc/ssl/cert.key
    required:
      - enabled
      - ssl_cert_path
      - ssl_key_path
  Backup:
    type: object
    properties:
      name:
        type: string
        example: generic-server
      paths:
        type: array
        items:
          - type: string
        example:
          - /var/lib/backups
          - /mnt/data
          - /etc
      exclusions:
        type: array
        items:
          - type: string
        example:
          - /etc/shadow
      target:
        type: array
        items:
          $ref: '#/definitions/BackupTarget'
      schedule:
        type: array
        items:
          - type: string
        example:
          - 05 01 * * *
      encrypt:
        type: boolean
        default: false
      encrypt_pass:
        type: string
      versioning:
        type: boolean
        default: false
      versions_max_num:
        type: integer
      versions_max_age:
        type: string
    required:
      - name
      - paths
      - targets
  BackupTarget:
    type: object
    properties:
      name:
        type: string
        example: aws_1
      type:
        type: string
        example: s3
      user:
        type: string
        example: AWS_ACCESS_KEY_ID
      pass:
        type: string
        example: AWS_SECRET_ACCESS_KEY
      bucket:
        type: string
        example: example-com-us-servers
      prefix:
        type: string
        example: backup/backups-for-server-51
      storage_class:
        type: string
        example: standard
    required:
      - name
      - type
      - bucket
      - prefix
  ApiResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
  ApiResponseGetConfig:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      result:
        $ref: '#/definitions/FullConfig'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
