swagger: '2.0'
info:
  description: >-
    This is the API which allows to configure, start, stop backups and view
    reports
  version: 1.0.0
  title: Cloudbackup API
basePath: /api/v1
tags:
  - name: config
    description: Configuration of the server and backups it does
  - name: backup
    description: 'Start, stop and see the status backups'
  - name: restore
    description: 'Start, stop and see the status restore operations'
  - name: report
    description: Reports about previous backups and restores
schemes:
  - http
  - https
paths:
  /config:
    post:
      tags:
        - config
      summary: Overwrite whole configuration
      description: >-
        If a password field is specified with value "******" (number of
        asterisks does not matter as long as it is only asterisks) then the
        actual password will be copied from the current running configuration.
        This is because when you fetch the configuration (via GET) passwords do
        not get printed. Any entries from the old configuration which are
        skipped or left out will be replaced with default values.
      operationId: writeAllCfg
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: daemon configuration
          required: true
          schema:
            $ref: '#/definitions/FullConfig'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
    get:
      tags:
        - config
      summary: Get the whole config
      description: >-
        Get the current active configuration. Password fields will have their
        values replaced with "**************" despite what the Swagger example
        shows below.
      operationId: getAllCfg
      produces:
        - application/json
      security: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponseGetConfig'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
  /config/backup:
    post:
      tags:
        - config
      summary: Overwrite an existing backup configuration or create a new entry
      description: >-
        Each individual backup entry needs to have a unique "name" entry. If a
        password field is specified with value "******" (number of asterisks
        does not matter as long as it is only asterisks) then the actual
        password will be copied from the current running configuration. This is
        because when you fetch the configuration (via GET) passwords do not get
        printed. Any entries from the "backup" section of old configuration
        which are skipped or left out will be replaced with default values.
      operationId: writeBackup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: backup section configuration
          required: true
          schema:
            $ref: '#/definitions/Backup'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
  /backup/list:
    get:
      tags:
        - backup
      summary: List backup jobs and their status
      description: >-
        Get the list of configured backup jobs and their status. If
        state="running" then the uuid field will contain the unique id of the
        running backup; otherwise the field is an empty string.
      operationId: BackupJobsList
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponseBackupList'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
  /backup/start:
    post:
      tags:
        - backup
      summary: Start a backup now.
      description: >-
        Start a backup job now. The selected backup job must not be already
        running. If the backup job is successfully started then the uuid field
        will contain the unique id of the running backup; otherwise the field is
        an empty string.
      operationId: BackupStart
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: name of the backup to start
          required: true
          schema:
            $ref: '#/definitions/BackupJobName'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponseBackupStart'
        '400':
          description: Backup already running
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: No backup job matches the provided name
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
  /backup/stop:
    post:
      tags:
        - backup
      summary: Stop a running backup.
      description: >-
        Stop a running backup. The selected backup job must be already running.
        You need to specify only the name of the backup job and any matching
        running job will be stopped. Optionally you can also specify an uuid
        associated with the backup name and only if the running backup job
        matches both name and id will then be the backup job stopped.
      operationId: BackupStop
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: name of the backup to stop and optionally the id
          required: true
          schema:
            $ref: '#/definitions/BackupJobNameAndId'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Client Error
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Basic authentication required
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
  /backup/dryrun:
    post:
      tags:
        - backup
      summary: Perform a dry run for a backup job.
      description: >-
         Performs a dry run backup job now. The purpose of this operation is to
         report back what files would be considered for backup, what would be 
         excluded and the exclusion rule which matched and also reports on 
         errors produced when trying to get file properties. The response is
         http2 Server Side Events and requires a client capable of consuming it.
         Response codes != 200 will be regular json while response code 200 will 
         be followed by http2 SSE. Each received event for the 200 status code 
         will be in the format "data: {json object}" except the last line at the 
         end of the input which will start with "data: Completed run:". Unfortunatelly 
         Swagger doesn't allow proper documentation of SSE so the response object 
         definition is the actual {json object} to be expected after the "data: " 
         field.
      operationId: BackupDryRun
      produces:
        - text/event-stream
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: name of the backup to start
          required: true
          schema:
            $ref: '#/definitions/BackupJobName'
      responses:
        '200':
          description: successful operation
          x-produces: text/event-stream
          schema:
            $ref: '#/definitions/ApiResponseBackupDryRun'
        '401':
          description: Basic authentication required
          x-produces: application/json
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: No backup job matches the provided name
          x-produces: application/json
          schema:
            $ref: '#/definitions/ApiResponse'
        '500':
          description: Internal Server Error
          x-produces: application/json
          schema:
            $ref: '#/definitions/ApiResponse'
      security: []
securityDefinitions:
  backup_auth:
    type: basic
    description: Use Basic Authentication
definitions:
  FullConfig:
    type: object
    properties:
      data_dir:
        type: string
        example: /var/lib/cloudbackup
      html_dir:
        type: string
        example: /usr/share/cloudbackup/webstatic
      user:
        type: array
        items:
          $ref: '#/definitions/User'
      http:
        $ref: '#/definitions/Http'
      https:
        $ref: '#/definitions/Https'
      backup:
        type: array
        items:
          $ref: '#/definitions/Backup'
  User:
    type: object
    properties:
      name:
        type: string
        example: testuser1
      pass:
        type: string
        example: $2a$05$Ug1eUCXbSYUvfnI6YokjReljCe2fZLYYhO4IQLuiu0/mnpBbsN2M.
      access:
        type: string
        example: write
        pattern: ^(read|write)$
  Http:
    type: object
    properties:
      bind_address:
        type: string
        default: '127.0.0.1:8080'
        example: '127.0.0.1:8080'
  Https:
    type: object
    properties:
      enabled:
        type: boolean
        default: false
      bind_address:
        type: string
        default: '127.0.0.1:8443'
        example: '127.0.0.1:8443'
      ssl_cert_path:
        type: string
        example: /etc/ssl/cert.crt
      ssl_key_path:
        type: string
        example: /etc/ssl/cert.key
    required:
      - enabled
      - ssl_cert_path
      - ssl_key_path
  Backup:
    type: object
    properties:
      name:
        type: string
        example: generic-server
      paths:
        type: array
        items:
          type: string
        example:
          - /var/lib/backups
          - /mnt/data
          - /etc
      exclusions:
        type: array
        items:
          type: string
        example:
          - /etc/shadow
      dereference:
        type: boolean
        default: true
      target:
        type: array
        items:
          $ref: '#/definitions/BackupTarget'
      schedule:
        type: array
        items:
          type: string
        example:
          - 05 01 * * *
      encrypt:
        type: boolean
        default: false
      encrypt_pass:
        type: string
        default: ''
      versioning:
        type: boolean
        default: false
      versions_max_num:
        type: integer
      versions_max_age:
        type: string
        example: 10w
    required:
      - name
      - paths
      - target
  BackupTarget:
    type: object
    properties:
      name:
        type: string
        example: aws_1
      type:
        type: string
        example: s3
      user:
        type: string
        example: AWS_ACCESS_KEY_ID
      pass:
        type: string
        example: AWS_SECRET_ACCESS_KEY
      bucket:
        type: string
        example: example-com-us-servers
      prefix:
        type: string
        example: backup/backups-for-server-51
      storage_class:
        type: string
        example: standard
    required:
      - name
      - type
      - bucket
      - prefix
  ResultBackupJobList:
    type: object
    properties:
      name:
        type: string
        example: generic-server
      state:
        type: string
        example: running
        pattern: ^(running|stopping|stopped)$
      start_time:
        type: string
        example: '2018-06-02T16:38:55.676712775+10:00'
        description: 'A start time of 0001-01-01T00:00:00Z is the equivallent of null time and should be ignored for jobs having "state"="stopped"'
      next_run:
        type: string
        example: '2018-06-03T16:38:55.676712775+10:00'
      job_id:
        type: string
        example: '163A61FE-2205-4EB2-A0CB-B19A033C1CE3'
        pattern: >-
          ^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}|)$
      stats_counters:
        type: object
        description: 'This object is present in replies only if the job "state" is not "stopped"'
        properties:
          examined_files:
            type: integer
            description: 'How many files had their properties examined. Excluded files (via the "exclusions" section) do not increment this counter.'
            example: 604
          examined_directories:
            type: integer
            description: 'How many directories had their properties examined. Excluded directories (via the "exclusions" section) do not increment this counter.'
            example: 23
          examine_produced_errors:
            type: integer
            description: 'While examining the properties of files and directories this may errors were encountered. Please get the logs for messages with level ERROR and WARNING produced by context="backup.scan" in order to get additional details. Items for which this counter got incremented also had one of "examined_files" or "examined_directories" incremented'
            example: 2
          excluded:
            type: integer
            description: 'How many files or directories where excluded due to matching some exclusion rule provided by the user (in the configuration file).'
            example: 7
          uploaded_files:
            type: integer
            description: 'How many files were uploaded so far during the run of this backup job'
            example: 230
          uploaded_directories_metadata:
            type: integer
            description: 'How many directories had their properties uploaded so far during the run of this backup job'
            example: 11
          upload_produced_errors:
            type: integer
            description: 'How many files and directories produced irrecoverable errors so far during the run of this backup job. This implies said files and directories were not successfuly backed up.'
            example: 11
      stats_text:
        type: object
        description: 'This object is present in replies only if the job "state" is not "stopped"'
        properties:
          current_directory:
            type: string
            description: "The current directory being processed by the backup job which is in progress. If the field is empty then no directory is currently processed or processing has completed"
            example: "/var/lib/application/data"
          current_file:
            type: string
            description: "The current file being processed by the backup job which is in progress. If the field is empty then no file is currently processed or processing has completed"
            example: "/var/lib/application/data/project.pdf"
  ResultBackupJobDryRun:
    type: object
    properties:
      name:
        type: string
        example: /var/www/web-data/file0.dat
        description: "Name of the file or directory being reported"
      type:
        type: string
        example: running
        pattern: ^(file|directory|unknown)$
        description: "Unknown is reported when the file was excluded by an exclusion rule as then its properties aren't fetched so it can't be determined if it was a file or directory. Unknown is also reported when an error was encountered when trying to get the properties so again it can't be established if it is a file or a directory"
      excluded:
        type: boolean
        example: true
        description: "If this file or directory matched an exclusion rule. If excluded then it will not be considered for a backup"
      exclusion_expr:
        type: string
        example: '/var/www/web-data/*.dat'
        description: 'The expression which matched the file or folder and caused it to be excluded from being considered for backup. This expression will correspond to one of the expressions mentioned in the configuration file. If $excluded==false then this will be an empty string'
      error:
        type: string
        example: 'open /etc/ssl/private: permission denied'
        description: "Empty string if no error was encountered and otherwise the error message produced when trying to get the file or directory properties"
  ResultBackupJobStart:
    type: object
    properties:
      name:
        type: string
        example: generic-server
      job_id:
        type: string
        example: 163A61FE-2205-4EB2-A0CB-B19A033C1CE3
        pattern: >-
          ^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}|)$
  BackupJobName:
    type: object
    properties:
      name:
        type: string
        example: generic-server
    required:
      - name
  BackupJobNameAndId:
    type: object
    properties:
      name:
        type: string
        example: generic-server
      job_id:
        type: string
        example: 163A61FE-2205-4EB2-A0CB-B19A033C1CE3
        pattern: >-
          ^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}|)$
    required:
      - name
  ApiResponse:
    type: object
    properties:
      code:
        type: string
        example: success
      message:
        type: string
        example: success
  ApiResponseGetConfig:
    type: object
    properties:
      code:
        type: string
        example: success
      message:
        type: string
        example: success
      result:
        $ref: '#/definitions/FullConfig'
  ApiResponseBackupList:
    type: object
    properties:
      code:
        type: string
        example: success
      message:
        type: string
        example: success
      result:
        type: array
        items:
          $ref: '#/definitions/ResultBackupJobList'
  ApiResponseBackupStart:
    type: object
    properties:
      code:
        type: string
        example: success
      message:
        type: string
        example: success
      result:
        $ref: '#/definitions/ResultBackupJobStart'
  ApiResponseBackupDryRun:
    $ref: '#/definitions/ResultBackupJobDryRun'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
