#!/bin/sh
#
# Refresh webstatic/ui/vendor/ — the browser-side runtime dependencies of the web UI.
#
# The UI deliberately ships its Preact/htm runtime in-repo instead of loading it
# from a CDN, so the UI works on airgapped/DMZ networks and so a third party can
# never inject script into a page that holds backup-server credentials.
#
# Sources are the ESM builds from node_modules (populated by "npm install" from
# the pinned package-lock.json). The only edit applied is removal of the trailing
# "//# sourceMappingURL=" comment: the .map files it points at are ~107 KB and are
# not shipped, and leaving the comment would make browser devtools request a file
# that does not exist. This is comment-only and does not change behaviour;
# vendor/MANIFEST.md records the upstream checksum so the copy stays verifiable.
#
# Usage:
#   ./vendor-deps.sh          refresh vendor/ in place
#   ./vendor-deps.sh --check  verify vendor/ matches node_modules (used by uitest)

set -e

cd "$(dirname "$0")"

CHECK=0
if [ "$1" = "--check" ]; then
    CHECK=1
fi

if [ ! -d node_modules/preact ] || [ ! -d node_modules/htm ]; then
    echo "ERROR: node_modules is not populated. Run 'npm install' in webstatic/ui first."
    exit 1
fi

# Guard against vendoring a version other than the one pinned in package-lock.json.
for pkg in preact htm; do
    installed=$(node -p "require('./node_modules/${pkg}/package.json').version")
    locked=$(node -p "require('./package-lock.json').packages['node_modules/${pkg}'].version")
    if [ "$installed" != "$locked" ]; then
        echo "ERROR: node_modules/${pkg} is ${installed} but package-lock.json pins ${locked}."
        echo "       Run 'npm ci' (or 'npm install') so the vendored copy matches the lockfile."
        exit 1
    fi
done

# source path under node_modules -> destination file name under vendor/
# Keep these in sync with the import map in index.html.
FILES="
preact/dist/preact.mjs:preact.mjs
preact/hooks/dist/hooks.mjs:preact-hooks.mjs
htm/dist/htm.mjs:htm.mjs
htm/preact/index.mjs:htm-preact.mjs
"

if [ "$CHECK" -eq 1 ]; then
    OUT=$(mktemp -d)
    trap 'rm -rf "$OUT"' EXIT
else
    OUT=vendor
    rm -rf "$OUT"
    mkdir -p "$OUT"
fi

MANIFEST="${OUT}/MANIFEST.md"

preact_version=$(node -p "require('./node_modules/preact/package.json').version")
htm_version=$(node -p "require('./node_modules/htm/package.json').version")

cat > "$MANIFEST" <<EOF
# Vendored web UI runtime dependencies

Generated by \`webstatic/ui/vendor-deps.sh\` — do not edit these files by hand.
Re-generate with \`make uivendor\` after bumping a version in \`package.json\`.

| Package | Version | License |
|---------|---------|---------|
| preact  | ${preact_version} | MIT (see LICENSE.preact) |
| htm     | ${htm_version} | Apache-2.0 (see LICENSE.htm) |

The trailing \`//# sourceMappingURL=\` comment is stripped from each file (the
\`.map\` files are not shipped). Nothing else is modified, so each vendored file
can be verified against npm by stripping that comment from the upstream build.

| Vendored file | Upstream path | Upstream sha256 | Vendored sha256 |
|---------------|---------------|-----------------|-----------------|
EOF

for entry in $FILES; do
    src="node_modules/${entry%%:*}"
    dst="${OUT}/${entry##*:}"
    sed -e 's|^//# sourceMappingURL=.*$||' -e '${/^$/d;}' "$src" > "$dst"
    printf '| `%s` | `%s` | `%s` | `%s` |\n' \
        "${entry##*:}" "${entry%%:*}" \
        "$(sha256sum "$src" | cut -d' ' -f1)" \
        "$(sha256sum "$dst" | cut -d' ' -f1)" >> "$MANIFEST"
done

cp node_modules/preact/LICENSE "${OUT}/LICENSE.preact"
cp node_modules/htm/LICENSE "${OUT}/LICENSE.htm"

if [ "$CHECK" -eq 1 ]; then
    if ! diff -r -q vendor "$OUT" >/dev/null 2>&1; then
        echo "ERROR: webstatic/ui/vendor/ is out of sync with node_modules."
        echo "       Run 'make uivendor' and commit the result."
        diff -r vendor "$OUT" || true
        exit 1
    fi
    echo "Vendored web UI dependencies are in sync (preact ${preact_version}, htm ${htm_version})."
else
    echo "Vendored web UI dependencies into webstatic/ui/vendor/ (preact ${preact_version}, htm ${htm_version}):"
    ls -l vendor
fi
